FitSNAP/FitSNAP

docs/PARALLEL.md
fitsnap3/__init__.py
fitsnap3/__main__.py
fitsnap3/deploy.py

Using either mpich or intel-mpi communication libraries, openmpi still in testing. Will require mpi4py 3.X or higher, conda or pip will handle this. LAMMPS will need to be re-compiled against these libraries as well. --mpi is now an optional command line switch that will allow --jobs # to exceed the cores on a single node. Coefficients and timings of example cases have been reproduced. Future improvements to a mpi-based training parser and linear solver will be needed to follow onto this PR.

Mpi dispatcher using mpi4py. (Nick Lubbers contributor)

---

fitsnap3/__main__.py
fitsnap3/geometry.py
fitsnap3/scrape.py

Adding kbar->bar conversion common to VASP training data. Also prints error units to screen based on lammps units type. `geometry.py` has just one hard coded conversion, will be tricky to enumerate the possible JSON-LAMMPS units conversions. Will be adding an example of how to construct JSON files from VASP outputs in a separate PR.

Unit Conversions from Training to LAMMPS styles

---

fitsnap3/runlammps.py

This version uses the recently released LAMMPS compute snap command. It is about 4x faster than before for the "Computing bispectrum data" stage. It is verified correct against:
examples/Ta_Linear_JCP2014/19Nov19_Standard
examples/WBe_PRB2019/19Nov19_Standard
There was a problem with:
examples/Ta_Quadratic_JCP2018/19Nov19_Standard
This has now been fixed in LAMMPS and a new PR submitted.

Updated compute-snap branch to master

---

docs/TEMPLATE.in
fitsnap3/__main__.py
fitsnap3/scrape.py

I have added a new option to use "smartweights" as opposed to weights in the grouplist file.  If used, the force, energy, and virial group weights are now inversely proportional to the number of rows present in the A matrix.  So for energy, force, and virials the smartweights for each group are:
energy ~ 1/(num_configurations)
forces~ 1/(num_atoms*3)
virials ~ 1/(num_configurations*6)
where num_configurations are the total number of configurations for each group and num_atoms is the total number of atoms across all configurations in each group.  
The default is to have smartweights off.  However, if smartweights are off and there is no grouplist defined, fitsnap will automatically use smartweights and create the grouplist for you.
I tested this for both Ta and W-Be by first creating a …

adding smartweights option

---

fitsnap3/__main__.py
fitsnap3/deploy.py
fitsnap3/linearfit.py
fitsnap3/runlammps.py
fitsnap3/scrape.py

Changed the way training and testing errors are computed.
Previously, the ||wAb-y|| problem contained both training and testing data but with w=0 for test data. Now it A and y are only constructed for the training set, the resulting b solution is then applied to a new A and y corresponding to the test data (no fit performed). 
There are now two metrics files printed, *_train *_test, self explanatory.
Grouplist file defines the training fraction, compute_testerrs of the input file defines the test fraction. 
wselfallflag (line 125 of runlammps.py) currently disabled since the LAMMPS master branch does not reflect this capability yet.

Clean Cross Validation

---

fitsnap3/io/sections/bispectrum.py
fitsnap3/scrapers/scrape.py
fitsnap3/scrapers/xyz_scraper.py

Add one hot column to blank2J after chem snap multiplication to preserve number of elements in blank2J w/ chem snap.

Fix chemsnap + bzeroflag=0 bug

---

fitsnap3/parallel_tools.py

These additions are for enabling the mliappy pair style model as a reference potential.
https://docs.lammps.org/pair_mliap.html

mliappy lammps-python enabled.

---

fitsnap3/parallel_tools.py

Example use case `run_fitsnap.py`
`$ cat run_fitsnap.py`
```from runpy import run_module
from mpi4py import MPI
import sys
comm = MPI.COMM_WORLD
rank = comm.Get_rank()
color = rank % 2
local_comm = comm.Split(color)
MPI.ADDED_COMM = local_comm
original_arguments = sys.argv[0]
new_arguments = ['fitsnap3', 'Ta-example.in', '--overwrite']
sys.argv = new_arguments
if color == 0:
run_module(sys.argv[0], run_name='__main__', alter_sys=False)
module_list = []
for module in sys.modules:
if 'fitsnap' in module:
module_list.append(module)
for module in module_list:
del sys.modules[module]
run_module(sys.argv[0], run_name='__main__', alter_sys=True)
sys.argv = original_arguments
```
change directory to `/path/to/fitsnap3/examples/Ta_Linear_JCP2014`
`$ mpirun -n 4 python /path/to/run_fitsnap.py`

add outside communicator using specific ADDED_COMM

---

fitsnap3/fitsnap.py
fitsnap3/solvers/solver.py

PyTorch examples will error at end of program because Output tries to process `solver.fit`, which is set to `None` when using PyTorch. Since the PyTorch module uses its own scheme for outputting model parameters, we can prevent the usual FitSNAP output from occurring for now.
There are other ways to fix this, curious if preventing Output is a bad idea.

Output fix with PyTorch.

---

fitsnap3/calculators/lammps_snap.py
fitsnap3/io/sections/calculator_sections/bispectrum.py
fitsnap3/io/sections/solver_sections/pytorch.py
fitsnap3/solvers/jax.py
fitsnap3/solvers/pytorch.py

Exception handling for MLIAP bugs which are unrelated to FitSNAP code: [https://github.com/lammps/lammps/issues/3204](https://github.com/lammps/lammps/issues/3204) 
This is a band-aid so that people can use FitSNAP until we fix the larger MLIAP issue. 
This allows users to run FitSNAP when they are not using nonlinear solvers (PyTorch or Jax).
Currently, nonlinear solvers can only be used if python is compiled and linked in a way that exports its symbols as dynamic, e.g. by building python from source with `./configure --enabled-shared`. 
This PR also includes inner cutoff capabilities.
Inner cutoff keywords can now be used in input scripts, e.g. for two atom types:
```
[BISPECTRUM]   
numTypes = 2   
switchinnerflag = 1
sinner = 0.9 0.9
dinner = 0.1 0.1
```

MLIAP exception handling.

---

fitsnap3/calculators/lammps_snap.py
fitsnap3/io/sections/calculator_sections/bispectrum.py
fitsnap3/io/sections/solver_sections/pytorch.py
fitsnap3/solvers/jax.py
fitsnap3/solvers/pytorch.py

Inner cutoff keywords can now be used in input scripts, e.g. for two atom types:
```
[BISPECTRUM]   
numTypes = 2   
switchinnerflag = 1
sinner = 0.9 0.9
dinner = 0.1 0.1
```
Default values and error catching prevents misuse.

Add inner cutoff options in bispectrum calculator.

---

examples/library/README.md
examples/library/extract_dataframe/example.py
examples/library/extract_descriptors/example.py
examples/library/loop_over_fits/example.py
examples/library/test_error_fit/example.py
examples/library/test_error_nofit/example.py
fitsnap3lib/parallel_tools.py
fitsnap3lib/solvers/pytorch.py

Fixes a bug that occurs when not using MPI. 
Parallel tools has a variable `self.check_fitsnap_exist` which was introduced in https://github.com/FitSNAP/FitSNAP/pull/120. This variable is a boolean setting to determine whether recreating dictionary keys is allowed, which is useful when using the library to loop over multiple fits. 
Currently `self.check_fitsnap_exist` is only declared for `stubs==0` (using MPI), but we also need to declare it when `stubs==1` (not using MPI). Otherwise we will get an error when running FitSNAP without MPI.

Fix parallel tools check_fitsnap_exist variable

---

tools/VASP2JSON.py

Small update to VASP2JSON.py script to skip ionic steps where the electronic structure wasn't converged - forces, total energy, and stresses aren't accurate for such steps. There's also a flag near the top you can change to get the old behavior, should you want it.
(Note, this script is just using whatever convergence criteria the VASP calculation was run at. It isn't checking the VASP convergence settings.)
Also, it now records the POTCAR files that were used in the calculation.
Also also, replaces all the "if" statements after the first with "elif"s, since they are all mutually exclusive.

updated VASP2JSON.py - skips unconverged ionic steps, records POTCARs

---

fitsnap3lib/scrapers/scrape.py

Should stop FitSNAP from dropping a random config or two from each group.
Full disclosure, I did not thoroughly test this. Just checked the formula and one test case.

fixed the rounding error in test/train split

---

tools/VASP2JSON.py
tools/VASPxml2JSON.py

New tool for making .json files from vasprun.xml files. 
Known bug with reading energy from VASP version 5.4 calculations (details in comments in file - fixable if becomes a problem, but fastest to just read the available entry if reading VASP 6.1 output).
Kind of hacky way of checking for convergence (may not function as intended for aiMD, might think a structure is unconverged if finishes converging on last step allowed by settings) - don't think there is an equivalent entry to what the OUTCAR reader looks for, but we could probably calculate the energy difference in last 2 scstep and compare to EDIFF setting (again, would be slightly slower). Also details in comments in code so we can address if becomes an issue.
Side note - VASP2JSON.py reads its positions from a summary area at the …

adding a VASP vasprun.xml to json conversion tool to the tools folder

---

fitsnap3lib/solvers/svd.py

dump_a() cannot be a static method as it is accessing the shared_arrays

---

docs/paper/paper.bib
docs/source/Tests.rst
fitsnap3lib/fitsnap.py
fitsnap3lib/solvers/solver.py

There is demand to write descriptors in a format ready for NN evaluation, without doing a fit. 
With linear models we use dataframes for this purpose.
For NNs, we write a pickled list of Configuration objects which can then be used by the user in library mode.
Examples will follow.

Write pickled configuration list when calculating descriptors for NNs

---

examples/library/transpose_trick/ace-Ta.py
examples/library/transpose_trick/ace-WBe.py
examples/library/transpose_trick/snap-Ta.py
examples/library/transpose_trick/snap-WBe.py
fitsnap3lib/fitsnap.py

The transpose trick example is included as an example of how to break down the A matrix into smaller parts, saving on memory and allowing different kinds of parallelization of fitting processes.
However, as currently implemented, it can only be performed on a single node due to a node check in `fitsnap.py`.
The node check is important to avoid fitting slowdowns when not using the ScaLAPACK solver, but also prevents us from using the transpose trick to its fullest potential.
This PR adds a simple check of the `multinode_testing` variable from the [EXTRAS] section into the ScaLAPACK node check.
If `multinode_testing` is set to 0 or not included, the node check will be performed as usual, and exit if > 1 node detected.
If `multinode_testing` is set to 1 and >1 node detected, a warning will …

Transpose trick example, add multinode capability

---

examples/library/genetic_algorithm/libmod_optimize.py
examples/library/genetic_algorithm/script_optimize.py
tools/input_to_settings_dict.py
tools/settings_dict_to_input.py

This PR is a minor overhaul of libmod_optimize.py in the genetic_algorithm (GA) library example.
The main goal is to add parallel processing of all "creatures" (the members of a population) within each generation using mpi4py.
Computing each generation's population in parallel leads to significant speedups* of the GA, allowing much higher throughput.
This is made possible by creating a second FitSNAP instance per generation that has a split MPI communicator.
To use: `mpirun -np P python script_optimize.py`
Note: that the genetic_algorithm will _increase_ the `population_size` variable to be compatible with the number of cores used!
Other changes in this PR include:
- Fixing a major bug in reshaping weight arrays 
- Adding more comments and documentation
- Updating convergence flag 
- …

Parallel genetic algorithm (with some other stuff)

---

examples/library/genetic_algorithm/libmod_optimize.py

Major bug fix for the genetic algorithm example (thanks to @jmgoff for flagging it) - 
The current scoring system is a sum of the RMSEs for energies, forces, and (if fitting) stresses. 
However, the best score is not matching that sum of RMSEs in the final fit's error file ("metrics.md" for example). 
It turns out the best group weights per generation are being recorded from the initial population variable, instead of the current generation's one - the final printed "best weights" output is thus incorrect.
Changes are all in libmod_optimize.py: 
1. Corrects the variable(s) tracking the best-scoring population member ("creature") per generation; and
2. Adds logic to ensure that stress fitting settings from user are enforced 
If you've been using this version of the GA (parallel), please …

Fix output bug in genetic_algorithm example

---

README.md
docs/source/Installation.rst

`compute pace` is now in the default lammps branch and not just separate forks of LAMMPS and ML-PACE.  Installation instructions should be updated so that they don't reference the first modified versions of LAMMPS and ML-PACE that allowed for ACE model training in FitSNAP. References to these outdated forks are removed from the docs as well as the README.
Using the existing installation instructions for "LAMMPS for FitSNAP" also enables ACE model training in FitSNAP.

update install doc following lammps update

---

fitsnap3lib/lib/neural_networks/pytorch.py
fitsnap3lib/lib/sym_ACE/gen_labels.py
fitsnap3lib/solvers/pytorch.py

For now, removes the reshape of the ` predicted_energy_total ` tensor - which leads to mismatch in tensor sizes later in PyTorch fits.
Adds a quick fix so that ACE examples (PyTorch or otherwise) can be ran even if 0 descriptors are generated based on lmin and lmax. More detailed warnings, graceful errors, and docs will be added in a later PR.

quick fix for PyTorch fits

---

fitsnap3lib/io/outputs/pace.py
fitsnap3lib/io/sections/calculator_sections/ace.py
fitsnap3lib/lib/sym_ACE/clebsch_tree.py
fitsnap3lib/lib/sym_ACE/coupling_coeffs.py
fitsnap3lib/lib/sym_ACE/wigner_tree.py
tools/default_ACE_settings.py

- Main change in this PR is to only evaluate (or load) the large CG and W3j libraries on the rank 0 comm. This was done in the `fitsnap3lib/lib/sym_ACE/coupling_cefficients.py` by loading in an instance of ParallelTools. Before, FitSNAP would load large pickle files from the sym_ACE library on every processor rather than just rank 0. For safety, the rank_zero decorator has been added to other functions in `fitsnap3lib/lib/sym_ACE/coupling_cefficients.py` that could lead to large pickle files in the future (the ones that generate the generalized coupling coefficient pickles in the working directory).
- Minor - updated the output for ACE potentials so that the 0th order label is not included when `bzeroflag` is set to `1`. Before this correction, outputs indicated that there was a 0th order …

Reduce memory overhead for large parallel ACE and minor label fix for ACE coefficient output

---

fitsnap3lib/lib/sym_ACE/yamlpace_tools/potential.py

This fix ensures the dtype of the output for ACE coefficients is np.float64 to be compatible with the Python JSON serializer for Numpy 2.0. 
Tested with the Ta_PACE example.
Thank you to Mary Alice Cusentino for flagging this bug!
\
\
More details:
With Numpy 2.0, scalars generated with Numpy are now represented as e.g. np.float64(...) to avoid confusion with native Python scalars, see [release note](https://numpy.org/devdocs/release/2.0.0-notes.html#representation-of-numpy-scalars-changed) on this change.
In at least one FitSNAP file so far, this representation change leads to some scalar values being cast to np.float32, which the native Python JSON serializer rejects with `TypeError: Object of type float32 is not JSON serializable`. 
This is a tiny fix but creating a PR for it for …

Update ACE output for Numpy 2.0 compatibility with JSON serializer

---

fitsnap3lib/scrapers/xyz_scraper.py

Making the xyz_scraper recognize the 'force' label as the same as 'forces', because it took me a bit to figure out the problem and I don't want others to hit the same road-bump.
Alternative fix could be a new set of if statements in the https://github.com/FitSNAP/FitSNAP/blob/318715c62b30d974271cdee991787b7c3dc57f88/fitsnap3lib/scrapers/xyz_scraper.py#L438 block that check for singular-plural mismatch.

Making xyz_scraper slightly more accommodating 

---

fitsnap3lib/calculators/lammps_snap.py
fitsnap3lib/parallel_tools.py

Main branch failing testing. Local tests indicate issues with data types in a few functions. No real investigation on initial PR submit, just fixes tested on Sandia machines with mpi and Python 3.12.
Changes:
- `lammps_snap.py` update: the LAMMPS SNAP compute we use can only accept integer arguments, but something in our FitSNAP pipeline now casts all bools to string bools "True, False". Added dict comprehension to change any string bools to int bools
- `parallel_tools.py` update: the `random.randint` function only accepts integer arguments, but the value `1e5` is type `float`. Did in-place cast to `int`. There was a fix to another `random` module function last year with Python version 3.11.6, this may be related?

Quick patch

---

.github/workflows/pytests.yaml

This PR updates the version of LAMMPS that is pulled and used by pytest to the Feature Release from June 2025 (tag = patch_12Jun2025).
Recent changes to lammps/python/lammps/pylammps.py in most recent develop branch (and upcoming stable branch) break FitSNAP linear fits.
This change will allow pytests here on GitHub to complete linear fits and ideally catch other underlying bugs.
A patch to FitSNAP itself to fix the underlying issue and ensure compatibility with the upcoming stable release of LAMMPS is planned in the near future.

Temporary: force LAMMPS pytest version to tag 'patch_12Jun2025'
