docs/TEMPLATE.in, fitsnap3/__main__.py, fitsnap3/bispecopt.py, fitsnap3/runlammps.py, fitsnap3/scrape.py, fitsnap3/serialize.py
I ran all of the current examples and compared snapcoeff files.
=> added chemsnap capabilities and changed charges option a bit

fitsnap3/__init__.py, fitsnap3/calculators/calculator.py, fitsnap3/calculators/lammps_snap.py, fitsnap3/fitsnap.py, fitsnap3/io/outputs/outputs.py, fitsnap3/io/sections/path.py, fitsnap3/parallel_tools.py, fitsnap3/scrapers/scrape.py
=> Memory features and error handling

docs/requirements.txt, fitsnap3/io/sections/groups.py, fitsnap3/io/sections/path.py, fitsnap3/io/sections/sections.py
There was a bug when I added the groups section that prevented the ability to choose your working directory.
=> Fix inability to choose working directory

README.md, docs/TEMPLATE.in, examples/Ta_Linear_JCP2014/Ta-example.in, examples/Ta_Linear_JCP2014/grouplist-Ta.in, examples/Ta_Quadratic_JCP2018/Ta-example.in, examples/WBe_PRB2019/WBe-example.in, fitsnap3/__init__.py, fitsnap3/__main__.py, fitsnap3/bispecopt.py, fitsnap3/deploy.py, fitsnap3/geometry.py, fitsnap3/linearfit.py, fitsnap3/runlammps.py, fitsnap3/scrape.py, fitsnap3/serialize.py
New error logs will give a full detail of every E,F,S used in the training and testing data. LAMMPS validation feature is still a beta feature and will require users to modify __main__.py to apply the correct SNAP potential used in validation. See lines 305-307 of main.
=> Clean Cross Validation, detailed error reporting

docs/TEMPLATE.in, examples/InP_JPCA2020/InP-example.in, examples/InP_JPCA2020/README.md, fitsnap3/calculators/calculator.py, fitsnap3/io/sections/solver.py, fitsnap3/parallel_tools.py, fitsnap3/scrapers/scrape.py, fitsnap3/scrapers/scraper_factory.py, fitsnap3/scrapers/xyz_scraper.py, fitsnap3/solvers/solver.py, fitsnap3/solvers/svd.py, fitsnap3/solvers/tensorflowsvd.py
Read extxyz files to process configs to fit on.
=> Xyz scraper

fitsnap3/calculators/lammps_snap.py, fitsnap3/io/sections/groups.py, fitsnap3/io/sections/outfile.py, fitsnap3/io/sections/path.py, fitsnap3/io/sections/sections.py, fitsnap3/parallel_tools.py
=> Clean Up Arguments

fitsnap3/io/outputs/original.py, fitsnap3/scrapers/scrape.py, fitsnap3/scrapers/xyz_scraper.py
Two little bugs that I spotted. I did not get a chance to test the examples before the Units PR was merged.
=> Fix small bugs

fitsnap3/solvers/svd.py
Check to see if matrix is ill conditioned for transpose trick.
=> Added proper check to see if transpose trick is viable for svd

fitsnap3/parallel_tools.py
=> Small Comm bug

tests/test_examples.py
Game plan is to add in all examples as pytest tests to have a convenient script to run and test all examples.
=> Pytest incorporation into FitSNAP

.github/workflows/python-package-conda.yml, tests/example_checker.py
Temporary placeholder for more extensible testing output.
Output currently outputs average coeff difference.
Note: Pytest + MPI + GitHub actions is a fragile framework combination for extracting output.
=> Pytest addition

tools/VASP2JSON.py
for conversion from VASP's OUTCAR/POSCAR to the .json file type used by FitSNAP.
=> adding VASP2JSON.py script to tools 

fitsnap3/calculators/calculator.py, fitsnap3/calculators/lammps_snap.py, fitsnap3/fitsnap.py, fitsnap3/io/outputs/outputs.py, fitsnap3/io/outputs/pace.py, fitsnap3/io/outputs/snap.py, fitsnap3/io/sections/calculator_sections/bispectrum.py, fitsnap3/io/sections/calculator_sections/calculator.py, fitsnap3/io/sections/outfile.py, fitsnap3/io/sections/sections.py, fitsnap3/io/sections/solver_sections/solver.py, fitsnap3/parallel_tools.py, fitsnap3/solvers/solver.py
Move descriptor, weights, and truths print to end of process configs instead of end of solvers, also added in bikflag
=> Minor Changes and improvements

tools/VASP2JSON.py
Thanks to Megan for finding the relevant line in the OUTCAR file!
=> updated VASP2JSON.py to only need an OUTCAR file (no more POSCAR file)

fitsnap3/fitsnap.py
All nonlinear solvers shouldn't have generic output.
=> General nonlinear solver output fix with warning message.

fitsnap3lib/scrapers/json_scraper.py
I fully acknowledge this is a pet peeve, but it really peeves me.
=> Allows FitSNAP to read .json files without comment lines without crashing.

README.md
=> update Conda install instructions with Sphinx

README.md
=> update to point to Installation.rst

examples/InP_VASP/InP-example_vasp.in
good to have the symlink tip in there
have tested it and updated this example:
- added symlink note directly to instruction set at top
- changed inline dataPath tip - current scraper expects directories not OUTCAR files (so it crashes with symlink to OUTCAR, this can be fixed later though)
=> small update to symlink tip

README.md, examples/Ta_PyTorch_NN/Ta-example.in, fitsnap3lib/calculators/calculator.py, fitsnap3lib/calculators/lammps_custom.py, fitsnap3lib/calculators/lammps_snap.py, fitsnap3lib/fitsnap.py, fitsnap3lib/io/sections/calculator_sections/bispectrum.py, fitsnap3lib/io/sections/solver_sections/network.py, fitsnap3lib/lib/neural_networks/descriptors/bessel.py, fitsnap3lib/lib/neural_networks/pairwise.py, fitsnap3lib/lib/neural_networks/pytorch.py, fitsnap3lib/parallel_tools.py, fitsnap3lib/solvers/network.py, fitsnap3lib/solvers/pytorch.py, fitsnap3lib/solvers/solver.py, fitsnap3lib/tools/dataloaders.py
Fixes https://github.com/FitSNAP/FitSNAP/issues/146, https://github.com/FitSNAP/FitSNAP/issues/148, and https://github.com/FitSNAP/FitSNAP/issues/150
=> Collected changes and fixes

fitsnap3lib/solvers/solver.py
more compact + easier implementation and adding in a split along the testing/training divide.
Left in the old *_error functions commented out since _config_error got that treatment. Also, feel free to remove the inline comments if they clash with intended code style.
=> updating solver.error_analysis() to .groupby.apply() and adding test/train split

fitsnap3lib/io/outputs/snap.py
#170 had `rcutfac` in place of `rfac0`.
=> Fix rcutfac

docs/source/Run/Run_input.rst, fitsnap3lib/lib/neural_networks/write.py, fitsnap3lib/solvers/pytorch.py
Small change to allow training on GPU but deployment on CPU.
Still need to fix #177 for deploying to LAMMPS on GPU; this might involve modifying LAMMPS ML-IAP instead.
=> Collected changes

docs/paper/paper.md
=> Fix paper affiliations

docs/paper/paper.md
=> Fix paper reference

docs/source/Installation.rst
=> for minimal conda install, update to 3.10

tools/input_to_settings_dict.py
Tiny PR to add a convenience script to the tools folder
=> added input file to settings dictionary tool

README.md, fitsnap3/__main__.py, fitsnap3lib/calculators/calculator.py, fitsnap3lib/calculators/lammps_snap.py, fitsnap3lib/fitsnap.py, fitsnap3lib/io/input.py, fitsnap3lib/io/outputs/snap.py, fitsnap3lib/parallel_tools.py, fitsnap3lib/solvers/anl.py, fitsnap3lib/solvers/pytorch.py, fitsnap3lib/solvers/ridge.py, fitsnap3lib/solvers/svd.py, pyproject.toml, tutorial.ipynb
Minor fixes/improvements caught over the IPAM hackathon.
=> Minor changes

fitsnap3lib/scrapers/json_scraper.py
old version depended on presence of terminating '/' in dataPath, this fixes it
=> fix group variable extract

fitsnap3lib/scrapers/scrape.py
fitting to stresses with smartweights on should divide 'vweight' by 6, not 'fweight'
=> fix smartweights stress bug

examples/library/genetic_algorithm/libmod_optimize.py, examples/library/genetic_algorithm/script_optimize.py
Here's the bulk of the changes for stress optimizing and also initial weights usage in the genetic algorithm code. There's a few functions I haven't updated yet (print final, simulated anneal, the internal part of the latin hypercube, though I think that doesn't need changes).
As implemented currently, this would always try to optimize stress even if user doesn't want that. We should make that part of the calculation optional before merging into main. Heading home for the weekend now, but figured I would put this up in case you guys want to work on it before I get to finishing it.
=> adding stress optimization and initial weight usage to genetic algo (WIP)

fitsnap3lib/calculators/lammps_base.py, fitsnap3lib/calculators/lammps_custom.py, fitsnap3lib/calculators/lammps_pace.py, fitsnap3lib/calculators/lammps_snap.py, fitsnap3lib/io/input.py, fitsnap3lib/io/outputs/snap.py, fitsnap3lib/io/sections/outfile.py, fitsnap3lib/lib/neural_networks/pytorch.py, fitsnap3lib/scrapers/scrape.py, fitsnap3lib/solvers/solver.py
This PR aims to fix/improve some input/output features of FitSNAP: 
- Error messages in the scrape and calculation steps have been updated to print a faulty configuration object's group and filename for easier debugging.
- Minor bugs with certain user-chosen input variables not being updated properly (for example, with Pytorch output_file names) have been squished.
- A FitSNAP instance's "config" object can differ quite a bit from original input "settings" object (file or Python dict) because FitSNAP adds and alters information based on the system settings, the type of fit, and so on. Two new functions have been added to `input.py` to let users see and use that information, "view_state" and "convert_to_dict."
=> Minor I/O fixes and improvements

examples/library/genetic_algorithm/script_optimize.py
Added the argparser back in for giving custom input filename.
(Give me a minute to test this. I made it in the browser and it seems I need to make the pull request before I can see the branch it made for it to actually test it?)
=> Update script_optimize.py in genetic algo

fitsnap3lib/io/sections/solver_sections/solver.py, fitsnap3lib/solvers/mcmc.py
This just adjusts the MCMC solver to match some internal syntax changes so that it is functional again.
=> updated MCMC solver to current solver template

.github/workflows/draft-pdf.yml, docs/source/Installation.rst, docs/source/Quick.rst, fitsnap3lib/calculators/lammps_base.py, fitsnap3lib/calculators/lammps_custom.py, fitsnap3lib/calculators/lammps_pace.py, fitsnap3lib/calculators/lammps_snap.py, fitsnap3lib/scrapers/json_scraper.py, fitsnap3lib/solvers/solver.py
A collection of small fixes and updates falling into two categories:
- Quality-of-life tweaks for docs and improved error reporting 
- Fixes to address GitHub workflow build failures and deprecation warnings
=> Small fixes and updates

docs/source/Installation.rst, docs/source/Run/Run_input.rst
- added [ACE] section in Run_input.rst
- added admonition boxes in Installation.rst
Resolves issues #256 and #259
=> documentation updates
